export const GeneralAction = {
    GENERAL_LANGUAGE: 'GENERAL_LANGUAGE',
    GENERAL_LAYOUT_S: 'GENERAL_LAYOUT_S',
    GENERAL_MEUNU_ACTIVE: 'GENERAL_MEUNU_ACTIVE',
    GENERAL_TOKEN_S: 'GENERAL_TOKEN_S',
    GENERAL_RESET_INFO: 'GENERAL_RESET_INFO',
  };
  